### ISSUE TITLE
Fails to compile on GHC 7.8  (even though claims to be compatible w/ base-4.7)

### ISSUE THREAD

**Issue by hvr** [michaelt/streaming#1]
See also http://matrix.hackage.haskell.org/package/streaming

```
[2 of 3] Compiling Streaming.Prelude ( Streaming/Prelude.hs, dist/dist-sandbox-ca80981b/build/Streaming/Prelude.o )

Streaming/Prelude.hs:170:25:
    Not in scope: type constructor or class ‘Foldable’
    Perhaps you meant ‘Foldable.Foldable’ (imported from Data.Foldable)

Streaming/Prelude.hs:171:27:
    Not in scope: type constructor or class ‘Traversable’

Streaming/Prelude.hs:258:21:
    Not in scope: type constructor or class ‘Foldable’
    Perhaps you meant ‘Foldable.Foldable’ (imported from Data.Foldable)

Streaming/Prelude.hs:692:26:
    Not in scope: type constructor or class ‘Foldable’
    Perhaps you meant ‘Foldable.Foldable’ (imported from Data.Foldable)
xcabal: Error: some packages failed to install:
streaming-0.1.0.9 failed during the building phase. The exception was:
ExitFailure 1
```

**Comment by michaelt** [comment]
Thanks very much, esteemed @hvr ! I added a .travis.yml to check for 7.8 and 7.6, which now seem to work.
